### ISSUE TITLE
unable to join hosted server

### ISSUE THREAD

**Issue by bubbyboom** [mymatsubara/osucraft#2]
idk if this is a problem on my end or with me or the server but i cant join cause i go to direct connection, ive tried many variations of localhost but it just says this
![image](https://github.com/mymatsubara/osucraft/assets/56478617/836dc2f4-685f-42a1-a306-b79fe7ae5717)
also it doesnt help that i dont know if im on the right version or not

**Comment by mymatsubara** [comment]
Uhm... not 100% sure. But I can think of two possible problems:
1. Are you using a 1.19.3 minecraft client?
2. Are you connecting to the server via the ip `127.0.0.1:25565`? (I had put the wrong address in the docs, my bad)
